language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install python-coveralls
  - pip install coverage
  - pip install nose   
script: pytest --cov=alirobi/Inverter
after_success:
  - coveralls